version: "3.8"
services:
    db:
        image: mysql:8.0
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
            - db_root_password
    wp:
        depends_on:
            - db
        image: wordpress:5-php7.4
        volumes:
            - ./html:/var/www/html
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
            - db_root_password
secrets:
    db_password:
        file: secrets/db_password.txt
    db_root_password:
        file: secrets/db_root_password.txt
