version: "3.8"
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
        volumes:
            - ./db:/var/db
        secrets:
            - db_password
            - db_root_password
        networks:
            - backend
    mailhog:
        image: mailhog/mailhog
        ports:
            - "127.0.0.1:1025:1025"
            - "127.0.0.1:8025:8025"
        expose:
            - 1025
        networks:
            - backend
    wp:
        depends_on:
            - db
        build: .
        volumes:
            - ./html:/var/www/html
        ports:
            - "127.0.0.1:8080:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
            XDEBUG_CONFIG: remote_host=host.docker.internal
        secrets:
            - db_password
            - db_root_password
        networks:
            - backend
secrets:
    db_password:
        file: secrets/db_password.txt
    db_root_password:
        file: secrets/db_root_password.txt
networks:
    backend: